#!/bin/sh
set -o errexit -o nounset

CONTEXTUAL_FILTER_PATH="./adguard/contextual.txt"
FILTER_URL="https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/UsefulAdsFilter/sections/usefulads.txt"

echo "! Title: Unblock Contextual Ads" >"$CONTEXTUAL_FILTER_PATH"
echo "! Original list $FILTER_URL" >>"$CONTEXTUAL_FILTER_PATH"
curl --proto '=https' --tlsv1.2 -sSf "$FILTER_URL" |
    grep '^\(!#\|#%#\)\|^@@||\(\(duckduckgo\|ebay\|etsy\)\.com\|ecosia\.org\)[/^]\|\(\(duckduckgo\|ebay\|etsy\)\.com\|ecosia\.org\)[^#]*#' |
    grep -v "^![^#]" |
    sed 's/^.*\b\(duckduckgo.com[,#]\)/\1/' |
    tr -d $'\r' >>"$CONTEXTUAL_FILTER_PATH"
echo "Wrote to '$CONTEXTUAL_FILTER_PATH'"
