#!/bin/sh
set -o errexit -o nounset

generate_filter() (
    url="$1"
    path="$2"
    title="$3"

    echo "! Title: $title" >"$path"
    echo "! Original list $url" >>"$path"
    curl --proto '=https' --tlsv1.2 -sSf "$url" |
        grep '^\(!#\|#%#\)\|^@@||\(\(duckduckgo\|ebay\|etsy\)\.com\|ecosia\.org\)[/^]\|\(\(duckduckgo\|ebay\|etsy\)\.com\|ecosia\.org\)[^#]*#' |
        grep -v "^![^#]" |
        sed 's/^.*\b\(duckduckgo.com[,#]\)/\1/' |
        tr -d $'\r' >>"$path"
    echo "Wrote to '$path'"
)

main() (
    contextual_filter_path="./adguard/contextual.txt"
    contextual_filter_url="https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/UsefulAdsFilter/sections/usefulads.txt"
    self_promo_filter_path="./adguard/self-promo.txt"
    self_promo_filter_url="https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/AnnoyancesFilter/Other/sections/self-promo.txt"

    generate_filter "$contextual_filter_url" "$contextual_filter_path" "Unblock Contextual Ads"
    generate_filter "$self_promo_filter_url" "$self_promo_filter_path" "Unblock Search Ads and Self-Promotion"
)

main
