#!/bin/sh
set -o errexit -o nounset

fetch() {
    curl --proto '=https' --tlsv1.2 -sSf --create-dirs "$@"
}

main() (
    echo "Updating source lists..."
    cookie_banner_tag="$(fetch "https://api.github.com/repos/mozilla/cookie-banner-rules-list/releases" | jq -r '.[0].tag_name')"
    fetch "https://raw.githubusercontent.com/badmojr/1Hosts/master/LICENSE" -o upstream/1hosts/LICENSE
    fetch "https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/LICENSE" -o upstream/adguard/LICENSE
    fetch "https://raw.githubusercontent.com/badmojr/1Hosts/master/Xtra/domains.txt" -o upstream/1hosts/xtra/domains.txt
    fetch "https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt" -o upstream/adguard/dns.txt
    fetch "https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_18_Annoyances_Cookies/filter.txt" -o upstream/adguard/annoyances-cookies.txt
    fetch "https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/UsefulAdsFilter/sections/usefulads.txt" -o upstream/adguard/usefulads.txt
    fetch "https://raw.githubusercontent.com/mozilla/cookie-banner-rules-list/$cookie_banner_tag/cookie-banner-rules-list.json" -o upstream/mozilla/cookie-banner-rules-list.json
    fetch "https://secure.fanboy.co.nz/fanboy-cookiemonster.txt" -o upstream/easylist/cookiemonster.txt
    fetch "https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/annoyances-cookies.txt" -o upstream/ubo/annoyances-cookies.txt
    fetch "https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/LICENSE" -o upstream/ubo/LICENSE
    echo "Done."
)

main
