#!/bin/sh
set -o errexit -o nounset

fetch() {
    curl --proto '=https' --tlsv1.2 -sSf --create-dirs "$@"
}

echo "Updating source lists..."
fetch "https://raw.githubusercontent.com/badmojr/1Hosts/master/LICENSE" -o upstream/1hosts/LICENSE
fetch "https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/LICENSE" -o upstream/adguard/LICENSE
fetch "https://raw.githubusercontent.com/badmojr/1Hosts/master/Xtra/domains.txt" -o upstream/1hosts/xtra/domains.txt
fetch "https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt" -o upstream/adguard/dns.txt
fetch "https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/UsefulAdsFilter/sections/usefulads.txt" -o upstream/adguard/usefulads.txt
echo "Done."
