name: Update
permissions:
  contents: write


# Controls when the workflow will run
on:
  schedule:
    - cron: "0 0 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4

      - name: Install ripgrep
        run: sudo apt-get install -y ripgrep

      - name: Install jq
        uses: dcarbone/install-jq-action@v2
        with:
          version: 1.7
          force: true

      - name: Update upstream filters
        run: scripts/update

      - name: Generate abp filters
        run: scripts/generate/abp

      - name: Generate cookie filters
        run: scripts/generate/cookies

      - name: Generate hosts filters
        run: scripts/generate/hosts

      - name: Generate Little Snitch filters
        run: scripts/generate/little-snitch

      - uses: EndBug/add-and-commit@v9
        with:
          message: "Update filters"
          default_author: github_actions
